
[package]
name = "news"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.1", features = ["blocking", "json"] }
serde = { version = "1.0.130", features = ["derive"] }
tokio = { version = "1.16.1", features = ["full"] }
rand = "*"
select = "*"

[features]
default = []