
[package]
name = "urban-dict"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
scraper = "*"
reqwest = { version = "0.11", features = ["blocking", "json"] }
